# Generated by Django 4.2.1 on 2023-06-03 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_alter_recipe_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='text',
            field=models.TextField(default='Описание рецепта2', verbose_name='Описание'),
            preserve_default=False,
        ),
    ]
