# Generated by Django 4.2.1 on 2023-06-12 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0013_shoppingcart_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='favoriterecipe',
            name='unique_user_favorite_recipe',
        ),
        migrations.AddConstraint(
            model_name='favoriterecipe',
            constraint=models.UniqueConstraint(fields=('user', 'recipe'), name='Рецепт уже есть в избранном', violation_error_message='Рецепт уже есть в избранном'),
        ),
    ]
