# Generated by Django 4.2.1 on 2023-06-12 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0014_remove_favoriterecipe_unique_user_favorite_recipe_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='shoppingcart',
            name='unique_user_shopping_cart',
        ),
        migrations.AddConstraint(
            model_name='shoppingcart',
            constraint=models.UniqueConstraint(fields=('user', 'recipe'), name='Рецепт уже есть в списке покупок', violation_error_message='Рецепт уже есть в списке покупок'),
        ),
    ]
