# Generated by Django 4.2.1 on 2023-06-10 10:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fanatic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fanatic', to=settings.AUTH_USER_MODEL, verbose_name='Подписчик')),
                ('idol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idol', to=settings.AUTH_USER_MODEL, verbose_name='Автор рецепта')),
            ],
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.UniqueConstraint(fields=('fanatic', 'idol'), name='unique_subscription', violation_error_message='Вы уже подписаны на данного автора!'),
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.CheckConstraint(check=models.Q(('idol', models.F('fanatic'))), name='idol_is_not_fan', violation_error_message='Невозможно подписаться на самого себя!'),
        ),
    ]
