# Generated by Django 4.2.1 on 2023-06-12 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='subscription',
            name='idol_is_not_fan',
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.CheckConstraint(check=models.Q(('idol', models.F('fanatic')), _negated=True), name='idol_is_not_fan', violation_error_message='Невозможно подписаться на самого себя!'),
        ),
    ]
